refactor(foundation): ensure distrobuilder is closer to default the default distrobuilder scripts (and the default image pulled from images.linuxcontainers.org (image:debian/buster/amd64)) work, but create failed units (cloud-final.service and systemd-journald-audit.socket). hopefully this will be fixed sometime, but in the meantime, provisioning scripts for these containers automatically reset-failed these services

diff --git a/foundation/distrobuilder/distrobuilder.yaml b/foundation/distrobuilder/distrobuilder.yaml
--- a/foundation/distrobuilder/distrobuilder.yaml
+++ b/foundation/distrobuilder/distrobuilder.yaml
@@ -1,14 +1,10 @@
 image:
-  name: debian-stretch-x86_64
   distribution: debian
   release: stretch
   description: |-
     debian {{ image.release }}
   architecture: x86_64
   variant: cloud
-
-mappings:
-  architecture_map: debian
 
 targets:
   lxc:
@@ -39,14 +35,17 @@ targets:
         content: |-
           lxc.arch = {{ image.architecture_personality }}
 
-# remember that config_get is processed by lcd
 files:
+  # override default hostname; later overridden by cloud init
   - path: /etc/hostname
     generator: template
     name: hostname
     content: |-
       {{ config_get("user.hostname", "localhost") }}
 
+  # this is overridden by cloud init, but required now
+  # so container has correct hostname during dns
+  # discovery on initial startup
   - path: /etc/hosts
     generator: template
     name: hosts
@@ -68,9 +67,10 @@ files:
   - path: /etc/network/interfaces
     generator: dump
     content: |-
-      # this file describes the network interfaces available on your system
-      # and how to activate them. for more information, see interfaces(5)
+      # This file describes the network interfaces available on your system
+      # and how to activate them. For more information, see interfaces(5).
 
+      # The loopback network interface
       auto lo
       iface lo inet loopback
 
@@ -81,26 +81,46 @@ files:
     types:
       - container
 
-  # - path: /etc/network/interfaces
-  #   generator: dump
-  #   content: |-
-  #     # this file describes the network interfaces available on your system
-  #     # and how to activate them. for more information, see interfaces(5)
+  - path: /etc/network/interfaces
+    generator: dump
+    content: |-
+      # This file describes the network interfaces available on your system
+      # and how to activate them. For more information, see interfaces(5).
 
-  #     auto lo
-  #     iface lo inet loopback
+      # The loopback network interface
+      auto lo
+      iface lo inet loopback
 
-  #     auto enp5s0
-  #     iface enp5s0 inet dhcp
+      auto enp5s0
+      iface enp5s0 inet dhcp
 
-  #     source /etc/network/interfaces.d/*.cfg
-  #   types:
-  #     - vm
-  #   releases:
-  #     - stretch
-  #     - buster
-  #     - bullseye
-  #     - sid
+      source /etc/network/interfaces.d/*.cfg
+    types:
+      - vm
+    releases:
+      - stretch
+      - buster
+      - bullseye
+      - sid
+
+  - path: /etc/network/interfaces
+    generator: dump
+    content: |-
+      # This file describes the network interfaces available on your system
+      # and how to activate them. For more information, see interfaces(5).
+
+      # The loopback network interface
+      auto lo
+      iface lo inet loopback
+
+      auto eth0
+      iface eth0 inet dhcp
+
+      source /etc/network/interfaces.d/*.cfg
+    types:
+      - vm
+    releases:
+      - jessie
 
   - path: /etc/default/grub.d/50-lxd.cfg
     generator: dump
@@ -119,6 +139,35 @@ files:
     types:
       - vm
 
+  # - name: meta-data
+  #   generator: cloud-init
+  #   variants:
+  #     - cloud
+
+  - path: /var/lib/cloud/seed/nocloud-net/meta-data
+    generator: template
+    name: cloud-init-meta
+    content: |-
+      instance-id: {{ container.name }}
+      local-hostname: {{ config_get("user.hostname", "localhost") }}
+      {{ config_get("user.meta-data", "") }}
+    template:
+      when:
+        - create
+        - copy
+    variant:
+      - cloud
+
+  - name: network-config
+    generator: cloud-init
+    variants:
+      - cloud
+
+  # - name: user-data
+  #   generator: cloud-init
+  #   variants:
+  #     - cloud
+
   - path: /var/lib/cloud/seed/nocloud-net/user-data
     generator: template
     name: cloud-init-user
@@ -135,61 +184,19 @@ files:
     variant:
       - cloud
 
-  - path: /var/lib/cloud/seed/nocloud-net/meta-data
-    generator: template
-    name: cloud-init-meta
-    content: |-
-      instance-id: {{ container.name }}
-      local-hostname: {{ config_get("user.hostname", "localhost") }}
-      {{ config_get("user.meta-data", "") }}
-    template:
-      when:
-        - create
-        - copy
-    variant:
+  - name: vendor-data
+    generator: cloud-init
+    variants:
       - cloud
 
-  - path: /var/lib/cloud/seed/nocloud-net/network-config
-    generator: template
-    name: cloud-init-network
-    content: |-
-      {% if config_get("user.network-config", "") == "" %}version: 1
-      config:
-        - type: physical
-          name: eth0
-          subnets:
-            - type: {% if config_get("user.network_mode", "") == "link-local" %}manual{% else %}dhcp{% endif %}
-              control: auto{% else %}{{ config_get("user.network-config", "") }}{% endif %}
-    template:
-      when:
-        - create
-        - copy
-    variant:
-      - cloud
+  - name: lxd-agent
+    generator: lxd-agent
+    types:
+      - vm
 
-  - path: /var/lib/cloud/seed/nocloud-net/vendor-data
-    generator: template
-    name: cloud-init-vendor
-    content: |-
-      {{ config_get("user.vendor-data", properties.default) }}
-    template:
-      when:
-        - create
-        - copy
-      properties:
-        default: |
-          #cloud-config
-          {}
-    variant:
-      - cloud
-
-  # - name: lxd-agent
-  #   generator: lxd-agent
-  #   types:
-  #     - vm
-  # - generator: fstab
-  #   types:
-  #     - vm
+  - generator: fstab
+    types:
+      - vm
 
 packages:
   manager: apt
@@ -197,12 +204,14 @@ packages:
   cleanup: true
   sets:
     - packages:
-        # - dialog
-        # - ifupdown
-        # - init
-        # - iproute2
-        # - locales
-        # - netbase
+        - dialog
+        - ifupdown
+        - init
+        - iproute2
+        # - isc-dhcp-client
+        - locales
+        - netbase
+        # - net-tools
         - openssh-server
         - vim.tiny
       action: install
@@ -231,6 +240,16 @@ packages:
         - amd64
 
     - packages:
+        - linux-image-4.9-amd64
+      action: install
+      types:
+        - vm
+      architectures:
+        - amd64
+      releases:
+        - jessie
+
+    - packages:
         - linux-image-amd64
       action: install
       types:
@@ -242,6 +261,15 @@ packages:
         - buster
         - bullseye
         - sid
+
+    - packages:
+        - grub-efi-arm64
+        - linux-image-arm64
+      action: install
+      types:
+        - vm
+      architectures:
+        - arm64
 
     - packages:
         - shim-signed
@@ -265,60 +293,69 @@ actions:
       #!/bin/sh
       set -eux
 
-      # disable networkd (unused)
+      # Disable networkd (unused)
       systemctl mask systemd-networkd.service
       systemctl mask systemd-networkd.socket
       systemctl mask systemd-networkd-wait-online.service
 
-      # make sure the locale is built and functional
+      # Make sure the locale is built and functional
       echo en_US.UTF-8 UTF-8 >> /etc/locale.gen
       locale-gen en_US.UTF-8 UTF-8
       update-locale LANG=en_US.UTF-8
 
-      # cleanup underlying /run
+      # Cleanup underlying /run
       mount -o bind / /mnt
       rm -rf /mnt/run/*
       umount /mnt
 
-      # cleanup temporary shadow paths
+      # Cleanup temporary shadow paths
       rm /etc/*-
-  # - trigger: post-files
-  #   action: |-
-  #     #!/bin/sh
-  #     set -eux
-  #     TARGET="x86_64"
-  #     [ "$(uname -m)" = "aarch64" ] && TARGET="arm64"
-  #     update-grub
-  #     # This will create EFI/BOOT
-  #     grub-install --uefi-secure-boot --target="${TARGET}-efi" --no-nvram --removable
-  #     # This will create EFI/debian
-  #     grub-install --uefi-secure-boot --target="${TARGET}-efi" --no-nvram
-  #     update-grub
-  #     sed -i "s#root=[^ ]*#root=/dev/sda2#g" /boot/grub/grub.cfg
-  #   types:
-  #     - vm
-  #   releases:
-  #     - buster
-  #     - bullseye
-  #     - sid
-  # - trigger: post-files
-  #   action: |-
-  #     #!/bin/sh
-  #     set -eux
-  #     TARGET="x86_64"
-  #     [ "$(uname -m)" = "aarch64" ] && TARGET="arm64"
-  #     update-grub
-  #     # This will create EFI/BOOT
-  #     grub-install --target="${TARGET}-efi" --no-nvram --removable --modules="part_gpt"
-  #     # This will create EFI/debian
-  #     grub-install --target="${TARGET}-efi" --no-nvram --modules="part_gpt"
-  #     update-grub
-  #     sed -i "s#root=[^ ]*#root=/dev/sda2#g" /boot/grub/grub.cfg
-  #   types:
-  #     - vm
-  #   releases:
-  #     - jessie
-  #     - stretch
+
+  - trigger: post-files
+    action: |-
+      #!/bin/sh
+      set -eux
+
+      TARGET="x86_64"
+      [ "$(uname -m)" = "aarch64" ] && TARGET="arm64"
+
+      update-grub
+      # This will create EFI/BOOT
+      grub-install --uefi-secure-boot --target="${TARGET}-efi" --no-nvram --removable
+      # This will create EFI/debian
+      grub-install --uefi-secure-boot --target="${TARGET}-efi" --no-nvram
+      update-grub
+      sed -i "s#root=[^ ]*#root=/dev/sda2#g" /boot/grub/grub.cfg
+    types:
+      - vm
+    releases:
+      - buster
+      - bullseye
+      - sid
+
+  - trigger: post-files
+    action: |-
+      #!/bin/sh
+      set -eux
+
+      TARGET="x86_64"
+      [ "$(uname -m)" = "aarch64" ] && TARGET="arm64"
+
+      update-grub
+      # This will create EFI/BOOT
+      grub-install --target="${TARGET}-efi" --no-nvram --removable --modules="part_gpt"
+      # This will create EFI/debian
+      grub-install --target="${TARGET}-efi" --no-nvram --modules="part_gpt"
+      update-grub
+      sed -i "s#root=[^ ]*#root=/dev/sda2#g" /boot/grub/grub.cfg
+    types:
+      - vm
+    releases:
+      - jessie
+      - stretch
+
+mappings:
+  architecture_map: debian
 
 source:
   downloader: debootstrap
